apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/b9b9f2k3/project3images
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: portfolio
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portfolio
  type: LoadBalancer
status:
  loadBalancer: {}